### ISSUE TITLE
AutoCheck  for  ShellCheck  Latest

### ISSUE THREAD

**Issue by TuxVinyards** [vscode-shellcheck/vscode-shellcheck#1036]
So,  today I  noticed that  VS Code  was  wanting to update this 'vscode-shellcheck' extension.    This made me think to check  Koalaman's  git pages  where I found out that  my version of  command line shellcheck  was  about 5 months out of date ...

Now, I suppose I could write an auto checking bash script and put it in start up.   Comparing  [https://github.com/koalaman/shellcheck/releases/latest](url)  to  `shellcheck -V` is pretty simple  ....   Like lots of others, I am using a distro with a six month update cycle & writing a checker would be less hassle, and possibly more stable, than changing OS to a rolling one.

The thing is, I only tend to use shellcheck when I am using VSCode, which makes me think that adding something into 'vscode-shellcheck' would be neater.   

I don't know enough TypeScript to write a routine for this, or even to say how easy it would be.  I am happy to write a bash script to do it though, if it could be integrated & people could use it.  Or maybe someone could see an easier way.   

Cheers.

**Comment by felipecrs** [comment]
We have this already if you use your own binary:

![image](https://user-images.githubusercontent.com/29582865/232045298-f6ac565c-4e25-42fa-a924-deeb30ce3a2e.png)

Make sure this setting is enabled. If it's not working or is not what you expect, let me know.

Also, the extension itself comes with its own (latest) shellcheck binary so you don't have to install and manage your own if you only plan to use it in VS Code.

**Comment by timonwong** [comment]
The version check currently in shellcheck only requires 0.7.0. Though bundled shellcheck now is the recommended way, should we bump the `BEST_TOOL_VERSION`?

**Comment by felipecrs** [comment]
Good catch! We definitely should bump it!

**Comment by TuxVinyards** [comment]
And maybe add something dynamic as '/latest' does resolve to a checkable
number ... Might save a lot of manual updating 👍

**Comment by felipecrs** [comment]
That should not be required, we usually are the first ones to update ShellCheck to the latest version when it's released. :)

**Comment by felipecrs** [comment]
Also, we don't want people to use ShellCheck versions that we did not test yet.

**Comment by TuxVinyards** [comment]
Hmm

**Comment by TuxVinyards** [comment]
Okay, for some reason I had 'shellcheck.disableVersionCheck'  set to true.  I must have done this for some obscure reason.  I can't remember but probably because vscode-shellcheck was hardcoded at v7 :rofl:

I suspect, as #1037 moves the hardcoded version ref  into the package dependencies list, that this fix will probably work okay, in practice.  As long as you keep up your enthusiastic maintenance @felipecrs   ....

I also searched  GitHub  to see if I didn't need to re-invent the wheel with a github checker.  I found one here that I might mod & build into a couple of other projects too:  [https://github.com/jansepke/github-release-checker/blob/master/github-release-checker](url)

:smiley:

**Comment by felipecrs** [comment]
Hey @TuxVinyards, thanks for the suggestion, but again, I don't want to ask users to update to a new version of ShellCheck that hasn't been tested against the extension. The new version of ShellCheck could cause the extension to break, for example.

If upgrading to newer versions of ShellCheck when they get released (which does not happen often) becomes a problem or start to take too long, we may instead consider adding RenovateBot to the repository so that it's upgraded automatically and will still be tested.
