### ISSUE TITLE
0.32.1 Throws repeated error on startup

### ISSUE THREAD

**Issue by reporter123** [vscode-shellcheck/vscode-shellcheck#1039]
TypeError: Cannot read properties of null (reading 'setResultCollections')
    at onDidCloseTextDocument (.../.vscode/extensions/timonwong.shellcheck-0.32.1-linux-x64/dist/extension.js:2:135241)

**Comment by felipecrs** [comment]
I could not reproduce it. Can you provide a document in which this issue is triggered?

**Comment by reporter123** [comment]
Not sure what was happening I'll let you if I can get it to happen again.
