### ISSUE TITLE
Duplicated messages due to the execution of two instances of shellcheck

### ISSUE THREAD

**Issue by xroberx** [vscode-shellcheck/vscode-shellcheck#1091]
This extension uses the bundled copy of shellcheck (or the one provided in the configuration) AND any other instance found in the PATH. This causes duplicates messages when hovering the mouse over any error. 

![screenshot](https://github.com/vscode-shellcheck/vscode-shellcheck/assets/1663186/c62e7368-804f-42f7-9ce6-fced2e49625c)

This is the output of strace (the relevant parts): 

> pid  1899<electron>] execve("/home/rober/.vscode-oss/extensions/timonwong.shellcheck-0.32.5-linux-x64/binaries/linux/x64/shellcheck", ["/home/rober/.vscode-oss/extensio"..., "-V"], 0x9f000775000 /* 56 vars */) = 0
[pid  1899<shellcheck>] +++ exited with 0 +++
[pid  1834<electron>] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=1899<shellcheck>, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
[pid  1911<electron>] execve("/home/rober/.vscode-oss/extensions/timonwong.shellcheck-0.32.5-linux-x64/binaries/linux/x64/shellcheck", ["/home/rober/.vscode-oss/extensio"..., "-f", "json1", "-"], 0x9f00033de00 /* 56 vars */) = 0
.
.
.
[pid  1914<electron>] execve("/usr/local/sbin/shellcheck", ["shellcheck", "--shell=bash", "--format=json1", "--external-sources", "--source-path=/home/rober/Projec"..., "-"], 0x190000ba9e00 /* 58 vars */) = -1 ENOENT (No existe el fichero o el directorio)
[pid  1914<electron>] execve("/usr/local/bin/shellcheck", ["shellcheck", "--shell=bash", "--format=json1", "--external-sources", "--source-path=/home/rober/Projec"..., "-"], 0x190000ba9e00 /* 58 vars */) = -1 ENOENT (No existe el fichero o el directorio)
[pid  1914<electron>] execve("/usr/bin/shellcheck", ["shellcheck", "--shell=bash", "--format=json1", "--external-sources", "--source-path=/home/rober/Projec"..., "-"], 0x190000ba9e00 /* 58 vars */) = 0

As you can see, it uses the bundled copy of shellcheck found in "/home/rober/.vscode-oss/extensions/timonwong.shellcheck-0.32.5-linux-x64/binaries/linux/x64/shellcheck" AND the copy found in "/usr/bin/shellcheck"

**Comment by felipecrs** [comment]
I bet you are affected by:

- https://github.com/bash-lsp/bash-language-server/issues/711

Can you please check?

**Comment by xroberx** [comment]
> I bet you are affected by:
> 
>     * [Auto disable linting functionality if ShellCheck vscode extension is installed bash-lsp/bash-language-server#711](https://github.com/bash-lsp/bash-language-server/issues/711)
> 
> 
> Can you please check?

Indeed, if I set bashIde.shellcheckPath to an empty string, there is only one entry instead of two. I thought the issue was due to the execution of two instances of shellcheck by this extension, as seen in strace's output...

**Comment by felipecrs** [comment]
> In fact, if I remove the shellcheck executable from /usr/bin, the issue is also fixed.

Yeah, that's how Bash IDE works.

Thus I'm closing then.
