### ISSUE TITLE
Drop support for non-webpack

### ISSUE THREAD

**Issue by felipecrs** [vscode-shellcheck/vscode-shellcheck#113]
I see that running with or without `webpack` is supported, and some code at `main.js` is because of that.

I suggest dropping support for non-webpack methods entirely. Do you think there is a reason to not do it?

**Comment by timonwong** [comment]
The main.js is mainly for measuring extension load time and easier for local development

**Comment by felipecrs** [comment]
webpack have the option `--watch`. `--mode development` can also help.

I'm just telling this because I felt confused when I started working with the repository first time, and reading the Vscode guides for bundling I felt that is not usual to have support non-bundling once bundling is there.

I can be wrong though. 

https://code.visualstudio.com/api/working-with-extensions/bundling-extension

**Comment by timonwong** [comment]
> I'm just telling this because I felt confused when I started working with the repository first time, and reading the Vscode guides for bundling I felt that is not usual to have support for non-bundling once bundling is there.

Yeah, It's a bit confusing, I introduced this pattern just because vscode developers use it:
-  https://github.com/microsoft/vscode-docker/blob/master/main.js
- https://github.com/microsoft/vscode-azurestorage/blob/master/main.js

**Comment by felipecrs** [comment]
https://github.com/vscode-shellcheck/vscode-shellcheck/pull/308
