### ISSUE TITLE
anormal ram consumption 

### ISSUE THREAD

**Issue by DevDorrejo** [vscode-shellcheck/vscode-shellcheck#1163]
Hello, today i was working normally in a shellscript project and at a moment the machine freeze have to force restart, so looking which process is affecting me, i found that is shellcheck:
![Screenshot_20230718_145520](https://github.com/vscode-shellcheck/vscode-shellcheck/assets/7697566/bc49086b-ced0-4ba7-aed8-6bd8fe4275af)

My Env:

OS: openSUSE Tumbleweed
VSCode: 1.80.1
ShellCheck extension: v0.33

my project:
![image](https://github.com/vscode-shellcheck/vscode-shellcheck/assets/7697566/36861b08-4772-4d5a-bf62-91a5adde1a1a)

**Comment by DevDorrejo** [comment]
reinstall the extesion looks like solve the issue.

**Comment by felipecrs** [comment]
How big are your files? By default the extension re-runs the shellcheck binary on every keystroke.

You can tweak this behavior to trigger only on save, if your files are very big and your computer can't handle them well.

**Comment by DevDorrejo** [comment]
my files size are of 12k to 150k, but reinstall solve the issue, thanks.
