### ISSUE TITLE
what is the use case for turning *off* "Use Workspace Root as Cwd"?

### ISSUE THREAD

**Issue by eplusminus** [vscode-shellcheck/vscode-shellcheck#1164]
Here's the problem I was seeing, which took me quite a while to figure out.

I have some scripts with `source` statements, and they're in a subdirectory of the project root. For simplicity let's say that they are all in `scripts/`.

Now, assuming that I normally run shellcheck from the project root directory, like `shellcheck scripts/*.sh`— which I think is a pretty normal way to use it, especially in CI— in order for the `# shellcheck source=` directive to work correctly, I would have to include the relative path from the project root, like this:

```
# shellcheck source=scripts/b.sh
source ./b.sh
```

I found that in Visual Studio Code, this would always get flagged as an error. The only way I could make it work _in the IDE_ was to change it to `source=b.sh` or `source=./b.sh`, removing the `scripts/` subpath. That's because, by default, the "Use Workspace Root as Cwd" setting is disabled and so it was running shellcheck on each file with the working directory set to the directory of that file. So there was no way I could make both the IDE and my CI job happy... until I realized that turning on "Use Workspace Root as Cwd" would give me the consistent behavior I wanted.

What I'm unclear on is... why isn't that the standard mode for the plugin? It seems unlikely to me that most people, when they have a project that has scripts in subdirectories, would use shellcheck by cd'ing into those subdirectories first. Maybe I'm just out of touch with common practices but I can't think why I would do that.

**Comment by felipecrs** [comment]
Honestly, I feel that it should also be made the default.

I had done that in v0.18.0: https://github.com/vscode-shellcheck/vscode-shellcheck/blob/master/CHANGELOG.md#0180-2021-10-20

But it brought some unintended consequences (broke some people's flow). I can't find the issue though.

Nevertheless, I can ask your question:

> what is the use case for turning *off* "Use Workspace Root as Cwd"?

Monorepos where you want to have different .shellcheckrc files per project/folder. In this case, the closest .shellcheckrc to the file would be used. Probably in this cases, if there is no .shellcheckrc in the workspace root, no shellcheckrc would be taken into account.
