### ISSUE TITLE
Exclude option is not working

### ISSUE THREAD

**Issue by tbhaxor** [vscode-shellcheck/vscode-shellcheck#1194]
I want to exclude [SC2155](https://www.shellcheck.net/wiki/SC2155) (which is working via command line, but not from the shellcheck

Startup logs
```
[2023-08-22T11:56:17.048Z] [DEBUG] Spawn: (cwd=/mnt/Projects/serenity) /usr/bin/shellcheck [
  '-f',
  'json1',
  '-x',
  'Ports/.hosted_defs.sh,Ports/.strip_env.sh,Ports/.port_include.sh',
  '-e SC2155',
  '-'
]
```

VScode configuration
```json
{
   "shellcheck.logLevel": "debug",
    "shellcheck.customArgs": [
        "-x",
        "Ports/.hosted_defs.sh,Ports/.strip_env.sh,Ports/.port_include.sh",
        "-e SC2155"
    ],
    "shellcheck.enableQuickFix": true,
    "shellcheck.enable": true,
    "shellcheck.run": "onSave",
    "shellcheck.useWorkspaceRootAsCwd": true,
    "shellcheck.executablePath": "/usr/bin/shellcheck"
}
```

![image](https://github.com/vscode-shellcheck/vscode-shellcheck/assets/28386721/3831306c-49e7-4d3e-b1dc-b7f8519e1a03)

I also tried reloading VScode, still this issue persists.

**Comment by tbhaxor** [comment]
I tried 2155, also provided in .exclude configuration. Still no effect.

**Comment by felipecrs** [comment]
May I know why do you have the script path as a shellcheck arg?

**Comment by felipecrs** [comment]
Can you explain such requirement? The VS Code extension automatically adds the file to the command line when running shellcheck, you don't need to add it yourself.

Try with:

```json
{
   "shellcheck.logLevel": "debug",
    "shellcheck.customArgs": [
        "-x",
    ],
    "shellcheck.exclude": [
      "2155"
    ]
    "shellcheck.enableQuickFix": true,
    "shellcheck.enable": true,
    "shellcheck.run": "onSave",
    "shellcheck.useWorkspaceRootAsCwd": true,
    "shellcheck.executablePath": "/usr/bin/shellcheck"
}
```

**Comment by tbhaxor** [comment]
I don't know that much about configuration. I use shellcheck manually, someone told me about this extension. I thought this aggressive config will solve the issue.

**Comment by felipecrs** [comment]
Well, you should not play with the configuration if you don't know about it. The default configuration should work out of the box.

Also, you should avoid setting any custom args or exclude through VS Code settings, always prefer doing that through directives or the .shellcheckrc file.

**Comment by tbhaxor** [comment]
`.shellcheckrc` worked, thank you for your support.

**Comment by timonwong** [comment]
Just FYI:

"shellcheck.customArgs": [
        "-x",
        "Ports/.hosted_defs.sh,Ports/.strip_env.sh,Ports/.port_include.sh",
        "-e SC2155"
    ],

"-e SC2155" is invalid here, instead you should:

"shellcheck.customArgs": [
        "-x",
        "Ports/.hosted_defs.sh,Ports/.strip_env.sh,Ports/.port_include.sh",
        "-e",
        "SC2155"
    ],

**Comment by felipecrs** [comment]
Nice catch!
