### ISSUE TITLE
Can't find extension in VSCode Extension search

### ISSUE THREAD

**Issue by bruce-c-liu** [vscode-shellcheck/vscode-shellcheck#1208]
Is there an issue with this extension's metadata or something?

I can't find it when searching for "SpellCheck" in VSCode's extensions sidebar. 
(I have the extension installed. No search filters applied.).
<img width="443" alt="Screenshot 2023-08-28 at 12 06 50 PM" src="https://github.com/vscode-shellcheck/vscode-shellcheck/assets/12869062/f3edb118-96b3-4b89-a91e-1379ff4a02a8">

**Comment by felipecrs** [comment]
I think you are a little confused... this extension is ShellCheck, not SpellCheck.

**Comment by bruce-c-liu** [comment]
Omg, this is embarrassing... 😅
