### ISSUE TITLE
Ability to suppress messages for a specific code (and time period?), whilst keeping highlight/underline/tooltip.

### ISSUE THREAD

**Issue by NAICOLAS** [vscode-shellcheck/vscode-shellcheck#1214]
I'm working on a project where I need to map out a lot of variables, and it it's rather annoying having to look at "this variable is unused" everywhere with bright yellow color and text everywhere (!).
I want to be able to remove the messages, but still keep the underline/tooltip and highlight.

Here's a snippet or screenshot that shows the problem:
![image](https://github.com/vscode-shellcheck/vscode-shellcheck/assets/4830413/9b4ce53b-d65e-490a-89d0-d082623dce15)

Here's what shellcheck currently says:
"_X_ appears unused. Verify use (or export if used externally).

Here's what I wanted or expected to see:
Only the underline/tooltip and the highlight would be great to see, without the message (!).

**Comment by timonwong** [comment]
I think it's reported by BashIDE or some other extension. This extension generally only gives you underline

**Comment by felipecrs** [comment]
Or maybe you are using Error Lens.

**Comment by NAICOLAS** [comment]
Hello!
You are absolutely correct!
My bad!

Error Lens is indeed the culprit! Thank you for making me realise!
