### ISSUE TITLE
can't run ShellCheck on vscode

### ISSUE THREAD

**Issue by ovledo** [vscode-shellcheck/vscode-shellcheck#1237]
Failed to run shellcheck: [undefined] Command failed with exit code 1: shellcheck -V
'shellcheck' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

I can't run ShellCheck

**Comment by felipecrs** [comment]
What platform? OS and arch. Anything on your settings?

**Comment by ovledo** [comment]
Vision: 1.82.2 (user setup)
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT ia32 10.0.19044
64-bit operating system, x64-based processor


I'm very sorry I don't know what happened, actually I was able to use this plugin normally for the first two days.Regarding this computer being equipped by the company, I have not modified any settings, or is there any setting in its system that triggers the disabling function?

**Comment by timonwong** [comment]
What's your system locale? You can bring up ⌘ line (Win+R, type "cmd" then enter)

Then:

cd %USERPROFILE%\.vscode\extensions
dir

In the output, find something like timonwong.shellcheck-xxxxxxx, then cd into that directory.

Then you should run  `cd binaries/win32/x64` and type `shellcheck.exe` to see what happens

**Comment by ovledo** [comment]
I tried to enter the folder you mentioned: timonwong.shellcheck-xxxxxxx,I can actually get into this folder, but in the next step,i can't fint "binaries/win32/x64"  .Displays that the system cannot find the specified path,and i try to re-install vscode

**Comment by ovledo** [comment]
just now i find that folder but i can't find shellcheck.exe.Maybe that's where the problem comes from

**Comment by felipecrs** [comment]
What is the version of the extension?

**Comment by felipecrs** [comment]
Are you running the extension in a remote environment or natively on Windows?

**Comment by felipecrs** [comment]
I just tested on Windows x64, and it's working for me using the bundled binary.

**Comment by ovledo** [comment]
Thanks for you help,I re-install vscode and it's working for me now.About that issue i surmise that the shellcherk.exe file is missing from that folder due to some system rule.And  i running the extension in a  natively on Windows but forget which version of the extension.There is no problem now because I solved the problem of not working by reinstalling the software.

Finally, I would like to thank you very much for the help you provided me today.

**Comment by felipecrs** [comment]
No problem. I hope it stays working forever. Have a great day!
