### ISSUE TITLE
Do not run ShellCheck until a shell file is opened

### ISSUE THREAD

**Issue by thernstig** [vscode-shellcheck/vscode-shellcheck#1320]
If having the extension installed but opening repositories that does not have the ShellCheck binary, this message is seen:

> The shellcheck program was not found (not installed?). Use the 'shellcheck.executablePath' setting to configure the location of 'shellcheck'

Most extensions do not warn like this. I made another issue on the Golang extension where they fixed this https://github.com/golang/vscode-go/issues/3038.

In effect the extensions should only warn when opening a shell file _or_ potentially not at all until invoked via command.´

The rationale for this is that many developers move between repositories and even computers when coding, where ShellCheck is not always installed.

**Comment by thernstig** [comment]
@felipecrs I apologize, I believe you are correct and I must have opened a file without thinking as I cannot reproduce.

I have another idea in this area, though, but will close this one and open a new.

**Comment by felipecrs** [comment]
Are you sure such setting isn't set at any settings level? user, devcontainer/machine, workspace, folder...

**Comment by felipecrs** [comment]
Which VS Code are you using? Which OS and architecture?

**Comment by thernstig** [comment]
@felipecrs I just assumed it would fall back to the bundled one even if one was configured (but not installed) but that does not seem to be the case. Maybe that is sensible. Closing this then, but if you feel there is something that could be done and that it anyway should fall back to the built-in one, please re-open.

**Comment by felipecrs** [comment]
Why would you configure such setting if you wanted it to use the bundled binary anyway? It does not make sense to me.

In fact, I can imagine scenarios like devcontainers where you want the extension to always use a given binary of shellcheck. Making it fallback to the bundled one would make it very hard to debug or to identify whether such binary is being used/working or not.

**Comment by thernstig** [comment]
It makes no sense, I am having a bad day. 😆  I opened a new git repo today seeing these things, and jumped the gun too quickly. The fixes should be done in this git repo.

**Comment by felipecrs** [comment]
Alright, no worries. Have a great day. :)
