### ISSUE TITLE
The shellcheck program was not found

### ISSUE THREAD

**Issue by Morriz** [vscode-shellcheck/vscode-shellcheck#1364]
Hi, the following binary exists:
```
/opt/homebrew/bin/shellcheck
```
and the path includes `/opt/homebrew/bin`, so why this error?
```
he shellcheck program was not found (not installed?). Use the 'shellcheck.executablePath' setting to configure the location of 'shellcheck'
```

**Comment by Morriz** [comment]
I am on Sonoma on an M3 with apple silicon

**Comment by felipecrs** [comment]
Before anything let me ask: any reason why don't you use the bundled binary?

**Comment by Morriz** [comment]
No clue, just been using that for many years. And since I don't have anything configured, and the bundled lib does not get used, something must be off...right?

**Comment by felipecrs** [comment]
We include binaries for Apple Silicon. Do you mind trying again with the latest version of the extension?

**Comment by felipecrs** [comment]
@Morriz, please let us know if this is still an issue.

**Comment by Morriz** [comment]
After removing the value `spellcheck` I now get 
```
[2024-04-17T09:43:15.059Z] [ERROR] triggerLintForEntireWorkspace: TypeError: Cannot read properties of undefined (reading 'ok')
[2024-04-17T09:43:15.615Z] [ERROR] onDidOpenTextDocument: TypeError: Cannot read properties of undefined (reading 'ok')
```

**Comment by Morriz** [comment]
at version `v0.37.1` and enabled globally

**Comment by Morriz** [comment]
never mind, ik was disabled in the workspace...it works ok now
