### ISSUE TITLE
shellcheck going awry and consuming GBs of memory on macOS

### ISSUE THREAD

**Issue by magicus** [vscode-shellcheck/vscode-shellcheck#1365]
Something has happened with vs-shellcheck on my system lately (since a week or two). I'm not sure if this is caused by a change in vs-shellcheck, in my environment, or if I possibly have opened specific shell scripts that trigger this behavior.

The situation is as follows: macOS pops up a dialog asking me to Force Quit applications since I'm running out of virtual memory. A quick check with `top -o mem` shows that I have two shellcheck processes running, each consuming like 30-80 (?) GB or so. I kill them, and everything resumes working normally.

I did not do any detailed debugging, but acted fast, out of fear that the entire system would go down and bring important work with it, so apologies if this bug report is a bit sketchy.

I prefer to open a bug at this stage, to see if this is a known problem, or if anyone else is experiencing this. If I get no responses, I'll try to fill in more detail each time this happens.

**Comment by timonwong** [comment]
Maybe a known issue since shellcheck 0.9:

https://github.com/koalaman/shellcheck/issues/2652
https://github.com/koalaman/shellcheck/issues/2721

**Comment by magicus** [comment]
That sound like it could be it.

If this is not properly fixed in upstream, maybe vs-shellcheck can add a watchdog if this starts happening?

**Comment by felipecrs** [comment]
I would not do it. shellcheck is not a dead project, they can fix it.

**Comment by magicus** [comment]
I understand and respect your stance. But the bug in upstream has been open for more than a year, with no apparent input from the developers, just more users complaining about the same problem. :(

**Comment by magicus** [comment]
I got [the following response](https://github.com/koalaman/shellcheck/issues/2652#issuecomment-1925499893) from the shellcheck main developer: 

> With [d80fdfa](https://github.com/koalaman/shellcheck/commit/d80fdfa9e8e738827a88505b26d3e596c0f0e875) you can specify `# shellcheck extended-analysis=false` to skip DFA in particularly large files (also works in rc files, and via `--extended-analysis=false`.

So, maybe a more reasonable request for vscode-shellcheck is to turn on `--extended-analysis=false` for files over a certain size or number of lines. (The bug report indicates this happens for scripts of > 20000 lines, with perhaps some outliers). Or at least provide an option for users to have that functionality turned on. I could forcefully turn it off for all shellcheck runs using an rc file, but that sounds like a shame to have to avoid that just due to a few bad apples.

**Comment by felipecrs** [comment]
From what I understood, you can simply add `# shellcheck extended-analysis=false` to the file you want to disable such analysis on.

**Comment by magicus** [comment]
Which unfortunately is not so easy with files generated by autoconf. :( But yeah, maybe that is an alternative. I'll check once a new version of shellcheck is released which contain the patch.

**Comment by timonwong** [comment]
We'll need to wait shellcheck new release (requires this commit:  https://github.com/koalaman/shellcheck/commit/d80fdfa9e8e738827a88505b26d3e596c0f0e875 )

Until then, users can disable DFA globally through "shellcheck.customArgs"  or just disable DFA for files using `# shellcheck extended-analysis=false`

In summary, we have to wait

**Comment by felipecrs** [comment]
@magicus you can also add `extended-analysis=false` to your `.shellcheckrc`. The extension now packages shellcheck 0.10.0 and therefore this issue can be closed now.
