### ISSUE TITLE
VSCode automatically updating setting: editor.codeActionsOnSave source.fixAll.shellcheck?

### ISSUE THREAD

**Issue by KUGA2** [vscode-shellcheck/vscode-shellcheck#1371]
Hi,

Today I started an old project with this extension enabled. When switching into my Devcontainer, where shellcheck is activated via `devcontainer.json`s `"extensions"`, it automatically changes my settings.json:

![image](https://github.com/vscode-shellcheck/vscode-shellcheck/assets/10581931/10fc02b7-9f1e-4f23-b9ad-61a60f30c786)

What is this setting? In the repos readme it still says `true`. What is `"explicit"`? Where can I find documentation about it?

ShellCheck plugin: v0.35.0
VSCode Version: 1.86.0

**Comment by felipecrs** [comment]
Oh, but you are right. README is outdated.

**Comment by KUGA2** [comment]
Thanks so far. But is there any documentation about the possible values? Do you know where I can find it?

**Comment by felipecrs** [comment]
Isn't the information in the link I sent enough?

![image](https://github.com/vscode-shellcheck/vscode-shellcheck/assets/29582865/ad5a4dbb-cc5c-45bd-961e-8befce8086a9)

**Comment by KUGA2** [comment]
I completely missed your link. I am very sorry for this inconvenience!

**Comment by felipecrs** [comment]
Don't worry. All good. :)
