### ISSUE TITLE
compatibility of v.0.35.0 and VS Code 1.86.0

### ISSUE THREAD

**Issue by gitsto** [vscode-shellcheck/vscode-shellcheck#1377]
Hello,

I'm using VS Code on WSL running Ubuntu 22.04 on Windows 11, 
I appréciate using ShellCheck extention, but I had an issue with latest VS Code version 1.86.0

When I try to click on button 'Install in WSL: Ubuntu', notification popup is showing this error message:

`Can't install 'timonwong.shellcheck' extension because it is not compatible with the current version of Visual Studio Code (version 1.86.0).`

Do you plan to release new ShellCheck extension version?

**Comment by felipecrs** [comment]
That's weird. It's working perfectly fine for me, vscode 1.86.1.

**Comment by felipecrs** [comment]
Can you please take some screenshots?

**Comment by felipecrs** [comment]
https://github.com/vscode-shellcheck/vscode-shellcheck/assets/29582865/785f8ee3-dcba-4e4d-930b-909dd206b07b



> That's weird. It's working perfectly fine for me, vscode 1.86.1. Including WSL and Remote SSH.

**Comment by gitsto** [comment]
> Can you please take some screenshots?
Thanks for your reply,
I updated VSCode to 1.86.2, then I tried to install it again, and this time it worked! 
so guess it worked since 1.86.1 too
