### ISSUE TITLE
"is referenced but not assigned" happens only on non fully-capitalized variables

### ISSUE THREAD

**Issue by idillon-sfl** [vscode-shellcheck/vscode-shellcheck#1379]
Here two small files.
test.sh
```shell
#!/bin/sh
. ./test2.sh
$dummy
$DUMMY
```
test2.sh
```shell
#!/bin/sh
export dummy=""
export DUMMY=""
```

Now if I look at test.sh, `$dummy` has a shellcheck warning, while `$DUMMY` has not. I tried different variations of capitalization, and only the fully capitalized name does not have the shellcheck warning.

![Screenshot from 2024-02-09 11-01-09](https://github.com/vscode-shellcheck/vscode-shellcheck/assets/92585455/8fa944e2-bb1f-45e5-aa1b-a828bd771cad)

I am not sure what is the expected behavior, but something seems to be wrong. Bash IDE finds the definition in every case. Meanwhile, if I remove `. ./test2.sh`, shellcheck properly gives the warning for `$dummy`, but it does not for `$DUMMY`, while I would expect to see one.

**Comment by felipecrs** [comment]
Also note that this extension calls `shellcheck` under the hoods. You can verify that `shellcheck` will provide the same feedback, meaning there is nothing wrong with this extension especifically.

You can of course join the crew of people who believe that shellcheck should have external-sources enabled by default or perhaps https://github.com/vscode-shellcheck/vscode-shellcheck/issues/883.

**Comment by ioioioio** [comment]
Got it. Someone opened an issue three weeks ago on shellcheck's repo: https://github.com/koalaman/shellcheck/issues/2904

**Comment by felipecrs** [comment]
I don't understand at all the relationship with this issue and https://github.com/koalaman/shellcheck/issues/2904,

**Comment by idillon-sfl** [comment]
You're right. Just a lot of confusion from side because I missed the note in [the doc](https://github.com/koalaman/shellcheck/wiki/SC2154):
```
Note: This message only triggers for variables with lowercase characters in their name (foo and kFOO but not FOO) due to the standard convention of using lowercase variable names for unexported, local variables.
```

**Comment by felipecrs** [comment]
Ok... anyway, have you tried my suggestion?

**Comment by felipecrs** [comment]
If this is still an issue, I can reopen.
