### ISSUE TITLE
Cooperate with Bats language support

### ISSUE THREAD

**Issue by KlfJoat** [vscode-shellcheck/vscode-shellcheck#1391]
I adore this extension. Thanks so much for creating and maintaining it!

In #983, the answer for the extension linting Bats files is to set them as ShellScript.

I have another super-useful VSC extension for Bats files, [`jetmartin.bats`](https://open-vsx.org/extension/jetmartin/bats).

That extension creates true Bats language support in VSC--it creates a new configured language called "Bats (Bash Automated Testing System)" associated with `*.bats`. It also has highlighting and some snippet support.

I think you can see the problem here... I cannot have my very useful Bats highlighting while also having my very useful Shellcheck linting on a Bats test at the same time.

I haven't tried the permanent solution mentioned in #983 because I think that sets all Bats files as ShellScript. So when I want to lint my Bats files, I disable `jetmartin.bats`, manually set the individual file as a ShellScript, then fix issues. I have 45 Bats files in this project so far, and it's barely an eighth completed.

Is there some way you can make the shellcheck extension work with Bats language support enabled? Thanks!

**Comment by felipecrs** [comment]
We expose an API for such purposes:

https://github.com/vscode-shellcheck/vscode-shellcheck/blob/master/doc%2FAPI.md

It should not be difficult to implement it in the bats extension. I suggest you give it a try yourself and perhaps send a PR to them if you like it.

**Comment by KlfJoat** [comment]
I appreciate the quick response.

I'm a shell scripter, not a coder. Considering I'm still struggling after 6 months to create a VSC injection grammar for a single keyword for the inline shell function documentation tool I use, I'm going to leave the VSC extension coding to y'all for now. :smile: 

I'll pass my request and link on to the Bats extension creator, though. 

Thanks!
