### ISSUE TITLE
Issue Persisting Despite ShellCheck Configuration

### ISSUE THREAD

**Issue by Thuna7** [vscode-shellcheck/vscode-shellcheck#1409]
I've configured the ShellCheck extension with the following ignore pattern:

"shellcheck.ignorePatterns": {
    "\*\*/.vscode-server/\*\*": true
}
However, I'm still encountering Problems with the following file:

~/.vscode-server/data/User/workspaceStorage/073f7e157f535776aa165b2f075bf852/yocto-project.yocto-bitbake/embedded-documents/c42156fb-8176-41de-9edb-4263f51e74fe.py

Do you have any suggestions on how to address this?

**Comment by felipecrs** [comment]
Although not the point of the issue, I wonder why it's running against a Python file to begin with. Did you configure vscode to make it recognize such Python file as Shell Script?

**Comment by Thuna7** [comment]
The issue arises due to another VS Code extension employing a homemade hacky technique, leading to the analysis of these files. Therefore, it is not an issue with the ShellCheck extension. As a result, I am closing this issue.
