### ISSUE TITLE
Doesn't respect file-wide "shell=" directive after shebang

### ISSUE THREAD

**Issue by fcharron** [vscode-shellcheck/vscode-shellcheck#1414]
In v0.10 of shellcheck, you can use `# shellcheck shell=busybox` to replace the existing shebang shell (in my case `#!/bin/sh`), given that on multiple platforms, `/bin/sh` resolves to something else (busybox ash on busybox, dash on debian, etc...).

However, when using it with this extension, I see a first pass of linting that uses the correct shell (given by the `# shellcheck` instruction), and a few seconds later, I see a bunch of warnings appearing for POSIX rules (which would only apply if I had the original shebang interpreted literally).

Here are the first lines of my file:

```shell
#!/bin/sh
# shellcheck shell=busybox
```

To confirm the issue comes from the extension, and not shellcheck itself, I called shellcheck manually like this `shellcheck <my-file>`, and I don't see all those POSIX warnings, only proper busybox ones.

**Comment by felipecrs** [comment]
Can you confirm Bash IDE is disabled first?

**Comment by felipecrs** [comment]
Also, can you confirm the version of the extension you are using?

Can you also provide a shell script where I can reproduce the problem?

**Comment by fcharron** [comment]
I think it was Bash IDE. I didn't know I had it installed!

With it disabled, I can no longer reproduce the problem. Thanks a lot!

**Comment by felipecrs** [comment]
Bash IDE is awesome and super useful, you just need to disable its shellcheck functionalities though.

- https://github.com/bash-lsp/bash-language-server/issues/711
