### ISSUE TITLE
Add config option for custom file extensions

### ISSUE THREAD

**Issue by cen1** [vscode-shellcheck/vscode-shellcheck#1445]
I would like shellcheck to also run on .sh.j2 (jinja templated bash scripts). There is only Ignore Patterns option but no Include Patterns.

**Comment by felipecrs** [comment]
Isn't this enough?

```jsonc
// .vscode/settings.json
{
  "files.associations": {
    "*.sh.j2": "shellscript"
  }
}
```

**Comment by cen1** [comment]
Looks good, ty
