### ISSUE TITLE
Loosing intellisense in vscode after printf command subtitution with math context

### ISSUE THREAD

**Issue by hkskoglund** [vscode-shellcheck/vscode-shellcheck#1446]
I am loosing access to intellisense after line: 

    msb2=$( printf "0x%02x" $(( "$1" >> 24 )) )

If I double quoute the printf argument then everything is fine

    msb2=$( printf "0x%02x" "$(( "$1" >> 24 ))" )

**Comment by felipecrs** [comment]
This extension does not provide any intellisense. You probably meant to report this somewhere else.

**Comment by hkskoglund** [comment]
You're right. After checking it not related to vscode-shellcheck (disabled the extension). Strangely, I don't get the popup of variables names etc after this particular printf line. It its probably something with vscode **editor.quickSuggestions** that gets deactivated.

**Comment by felipecrs** [comment]
Probably Bash IDE then.
