### ISSUE TITLE
outdated in open vsx registry

### ISSUE THREAD

**Issue by GitMensch** [vscode-shellcheck/vscode-shellcheck#146]
I don't know if "someone" just uploaded a version two months ago or if you did that:
https://open-vsx.org/extension/timonwong/shellcheck

In any case it is very useful to have the extension available there (up-to-date), therefore: please co-publish to [Open VSX Registry](https://open-vsx.org/?search=notes).

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by felipecrs** [comment]
Thank you very much. We'll certainly work to publish in Open VSX every time we upload it to VS Marketplace. 

However, this work needs to be done at https://github.com/raix/semantic-release-vsce/issues/62 first.

**Comment by GitMensch** [comment]
Is that something like https://github.com/HaaLeo/publish-vscode-extension#readme or more?
Who is "you" that is targeted in your "would be welcome" note?

**Comment by felipecrs** [comment]
> Is that something like https://github.com/HaaLeo/publish-vscode-extension#readme or more?

Not exactly. The releases of this extension are managed by semantic-release. The semantic-release-vsce is a plugin that publishes to VS Marketplace based on semantic-release's decision.

> Who is "you" that is targeted in your "would be welcome" note?

@timonwong, I rewrote the comment to make it clearer.

**Comment by GitMensch** [comment]
> > Who is "you" that is targeted in your "would be welcome" note?
> 
> It's @timonwong.

If you can set this field you may want to use "assign to" then.

**Comment by felipecrs** [comment]
FYI https://github.com/felipecrs/semantic-release-vsce/pull/169 is WIP

**Comment by GitMensch** [comment]
Hey @github-actions bot, would be wonderful if you could include https://open-vsx.org/extension/timonwong/shellcheck in your release view ;-)

**Comment by felipecrs** [comment]
Hahaha, I also think so. But unfortunately, it's not currently possible: https://github.com/semantic-release/semantic-release/issues/2123

Unless I decouple the `ovsx` from the `semantic-release-vsce`, and create a `semantic-release-ovsx`.
