### ISSUE TITLE
Syntax coloring broken by bash bitwise shift left << in arithmetic expansion $(( ))

### ISSUE THREAD

**Issue by theknowledge** [vscode-shellcheck/vscode-shellcheck#1512]
All code that follows a bitwise shift left << inside an arithmetic expansion $(( )) appears orange, as if a comment.

E.g.

#!/bin/bash
echo "Good coloring"
A=$(( B >> 4 ))
echo "still ok"
A=$(( B << 4 ))
echo "Bad coloring"
echo "to end of file"

![image](https://github.com/vscode-shellcheck/vscode-shellcheck/assets/11996128/7fdb6cf7-3cc1-4f23-8e38-5124de9783ad)

Shellcheck v0.37.1
vscode 
Version: 1.90.2 (system setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by felipecrs** [comment]
This extension doesn't color anything.
