### ISSUE TITLE
Force use of bundled shellcheck

### ISSUE THREAD

**Issue by VoodaGod** [vscode-shellcheck/vscode-shellcheck#1523]
the container i am working in provides on old shellcheck version, that the extension is asking me to update for better compatibility.
would be nice to just tell the extension to use the bundled version it surely is happy with.

**Comment by felipecrs** [comment]
This is already the default behavior, unless you changed executable path setting.

**Comment by VoodaGod** [comment]
huh i checked and realized i wasn't seeing all settings because i was only looking at the "User" settings:
```
Shellcheck: Executable Path
Path to the `shellcheck` executable (bundled binaries will be used if empty).
```
however it is empty and i still get the message.
the extension seems to only have downloaded the windows version of shellcheck though:
```
ls .vscode-server/extensions/timonwong.shellcheck-0.37.1/binaries
win32
```
possibly the extension is getting confused because i am using vs code under windows, connected to linux via ssh, connected to a docker container?

anyway, i found this setting:
```
Shellcheck: Disable Version Check
Whether to disable shellcheck binary version check, which prompts for updating when an outdated version is found.
```
so i won't be bothered by the message anymore, thanks ;)

**Comment by felipecrs** [comment]
This is seems weird. Are you using Remote - SSH with devcontainers?

The extension runs in the remote host, meaning it will download the Linux binary. I use it everyday this way (Windows frontend, Linux SSH backend and devcontainer).

Unless you manually overrode the extension context to make it run on the frontend context (Windows) instead of in the the remote context. (I don't recall the name but vscode has a setting for that).

**Comment by VoodaGod** [comment]
vs code was telling me that the "extension is enabled in the remote host ..." and i could see that it was greyed out in the local extension menu, and active in the container extension menu.

i reinstalled the extension in the container extension menu, and et voila it seems to have downloaded the correct extension
```
ls .vscode-server/extensions/timonwong.shellcheck-0.37.1-linux-x64/binaries/
linux
```
but the other one is still there, too 🤷‍♂️:
```
ls .vscode-server/extensions/timonwong.shellcheck-0.37.1/binaries
win32
```

**Comment by felipecrs** [comment]
> but the other one is still there, too 🤷‍♂️:

Are you saying it should not? Perhaps this is more a question to VS Code itself. The extension play no role during installation or uninstallation of it.

**Comment by VoodaGod** [comment]
to my naive mind, uninstalling an extension would remove it, yes ;) but i guess it's a lot more complicated

**Comment by felipecrs** [comment]
I'm not very sure what's happening as well, I also believe it's weird you ended up with a win32 extension downloaded on your Linux machine.

**Comment by felipecrs** [comment]
On my Linux remote host I have only the linux one:

![image](https://github.com/vscode-shellcheck/vscode-shellcheck/assets/29582865/e413bacb-356c-4f13-a6a5-e5d4b642a294)
