### ISSUE TITLE
high memory and cause vscode killed by system

### ISSUE THREAD

**Issue by lazebird** [vscode-shellcheck/vscode-shellcheck#1538]
ShellCheck v0.37.1
vscode:
版本: 1.91.1
提交: f1e16e1e6214d7c44d078b1f0607b2388f29d729
日期: 2024-07-09T22:08:12.169Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.1.0-23-amd64

**Comment by lazebird** [comment]
![image](https://github.com/user-attachments/assets/0c01653e-6d51-4975-90b5-8d30b28f957c)

**Comment by timonwong** [comment]
try disable extended analyais: https://github.com/vscode-shellcheck/vscode-shellcheck/issues/1365#issuecomment-1926379787

**Comment by lazebird** [comment]
> try disable extended analyais: [#1365 (comment)](https://github.com/vscode-shellcheck/vscode-shellcheck/issues/1365#issuecomment-1926379787)

thanks, it works after i add custom arg '--extended-analysis==false' in settings
but my extension is already the newest 0.37.1, i don't know the version of shellcheck binary, but it should be 0.10 and this bug should not exist?

**Comment by timonwong** [comment]
@lazebird since 0.37.1 it just means you **are able** to disable extended analysis.
