### ISSUE TITLE
Checking large shell script file, such as binutls-gdb/configure or gcc/configure, will exhausts remote host's memory quickly

### ISSUE THREAD

**Issue by Jamwe** [vscode-shellcheck/vscode-shellcheck#1539]
Type: <b>Bug</b>

After using VSCode to connect to a remote host via SSH jump and opening the [binutls-gdb](https://sourceware.org/gdb/current/) project, ShellCheck will quickly exhaust the remote host's memory.

Scenario:
    environment: VSCode<=SSH=>SSH jump<=SSH=>remote host

Reproduction: 
    1. Open the terminal on the remote host, enter the `top `command, and then enter `M` to sort by memory usage;
    2. After connecting to the remote host mentioned above, open the [binutls-gdb](https://sourceware.org/gdb/current/) project on that host.

Phenomenon: It can be seen that ShellCheck's memory usage rapidly increases and eventually exhausts the remote host's memory.

**update: my mistake, see replies below**
~~Exception:
    1. In the above scenario, if you open other projects, such as [gcc](https://gcc.gnu.org/git.html), there will be no problem.
    2. In the scenario where SSH jump is not used, there is no problem opening the [binutls-gdb](https://sourceware.org/gdb/current/) project.~~

Extension version: 0.37.1
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by felipecrs** [comment]
How do you connect to the target environment in both cases, is it by using the [Remote - SSH extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)?

**Comment by felipecrs** [comment]
I'm just wondering as well about this:

> In the scenario where SSH jump is not used

If you can avoid using the SSH jump, why would you use it?

**Comment by felipecrs** [comment]
Got it. The next step to figure this issue out is to isolate whether the vscode extension causes the issue or the shellcheck CLI (which the extension makes use).

Can you try downloading shellcheck in your VM and running it from the terminal to scan the project and observe the use of memory?

Both SSH and SSH with Jump.

**Comment by felipecrs** [comment]
@Jamwe, I believe you ran into:

You can work around it by disabling extended analysis: https://github.com/vscode-shellcheck/vscode-shellcheck/issues/1365#issuecomment-1985023560

This issue is tracked at shellcheck CLI at: https://github.com/koalaman/shellcheck/issues/2652
