### ISSUE TITLE
Support ZSH with zshsweep

### ISSUE THREAD

**Issue by jordantrizz** [vscode-shellcheck/vscode-shellcheck#1540]
Has anyone looked into bringing in zshsweep as a linter for .zsh files?

https://github.com/psprint/zsh-sweep

https://github.com/psprint/zsh-sweep/issues/4

**Comment by felipecrs** [comment]
I'm very happy to learn there's now a linter for ZSH.

However, it's beyond this extension business.

This extension's purpose is to be a companion for shellcheck.

I guess it would make more sense if a new extension for zsh-sweep gets developed.

**Comment by jordantrizz** [comment]
> I guess it would make more sense if a new extension for zsh-sweep gets developed.

That would be the reasonable choice, I personally don't know how much of an undertaking it would be so I figured I'd throw out the idea of making it an option with this extension. But as you said, that's not the purpose of this plugin.
