### ISSUE TITLE
All diagnostics doubled in Problems view

### ISSUE THREAD

**Issue by silverqx** [vscode-shellcheck/vscode-shellcheck#1541]
Hi, I invoked the `ShellCheck: ShellCheck: Collect Diagnostics For Current Document` and now I have all diagnostics doubled in the Problems view, how this works I don't get it, can I somehow **quickly** remove them? Thx for suggestion

**Comment by felipecrs** [comment]
I bet you're getting diagnostics from Bash IDE:

- https://github.com/vscode-shellcheck/vscode-shellcheck/issues/916#issuecomment-1416829538

**Comment by silverqx** [comment]
Ok, I get it, thx for asap reply, I want to ask are there any advantages to using this extension over that in the Bash IDE? I see that this has many more settings.

**Comment by felipecrs** [comment]
Check this comment:

- https://github.com/vscode-shellcheck/vscode-shellcheck/issues/920#issuecomment-1417979730

**Comment by silverqx** [comment]
Thx, thats all what I need, its clear now.
