### ISSUE TITLE
Add severity option

### ISSUE THREAD

**Issue by cirelli94** [vscode-shellcheck/vscode-shellcheck#183]
It would be great to be able to set the `severity` in settings, like `--severity` option in the CLI.
Sometimes I feel overwhelmed by the errors, I'd like to start removing the errors, than the warnings, and so on... :)

**Comment by felipecrs** [comment]
It would be good if this could be set in `.shellcheckrc`.

**Comment by felipecrs** [comment]
@cirelli94 you can already do this:

```json
// .vscode/settings.json
{
    "shellcheck.customArgs": [
        "--severity=error"
    ]
}
```

**Comment by cirelli94** [comment]
@felipecrs thanks!
