### ISSUE TITLE
Option to turn optional tests on

### ISSUE THREAD

**Issue by jsuelwald** [vscode-shellcheck/vscode-shellcheck#185]
Hi,

the command line version does have the `-o` - parameter to enable optional tests. 

Setting "Custom Args" with `-o all` does not enable this feature

**Comment by timonwong** [comment]
You should split -o all into multiple args, for example:

![image](https://user-images.githubusercontent.com/1398228/111958143-dc3e7c00-8b27-11eb-9636-248e4efa1566.png)

![image](https://user-images.githubusercontent.com/1398228/111958098-ce88f680-8b27-11eb-9b81-1612b3656d1d.png)

Or just `--enable=all`
