### ISSUE TITLE
Add VS Code Link to Github Project Settings or README

### ISSUE THREAD

**Issue by coolaj86** [vscode-shellcheck/vscode-shellcheck#189]
Perhaps should link to <https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck> so that people know they're the same thing and can just click, click, next and be done. :)

**Comment by felipecrs** [comment]
Closing as per https://github.com/vscode-shellcheck/vscode-shellcheck/pull/190#issuecomment-912501421. @coolaj86 if you still believe that's not enough, feel free to comment.
