### ISSUE TITLE
Disable strikethrough for backtick command substitution

### ISSUE THREAD

**Issue by sweetgiorni** [vscode-shellcheck/vscode-shellcheck#192]
I love this extension, but oh my god does it frustrate me when I need to look at a file and I can't read it

![image](https://user-images.githubusercontent.com/12527888/114637395-14942e80-9c7e-11eb-9228-820607574aa6.png)

Even if there is an option to disable this, I think it should be disabled by default (if not removed entirely)

Again, I love you, but please

**Comment by felipecrs** [comment]
Backticks are deprecated in bash, as you probably know. How about using the https://marketplace.visualstudio.com/items?itemName=foxundermoon.shell-format altogether? It automatically fixes this issue.

**Comment by sweetgiorni** [comment]
Well I work on a large, old codebase and I don't particularly care to run an automatic formatter on hundreds of fragile shell scripts, especially since there's no actual benefit to doing it as far as I know. 

But I think that's beside the point. Ignoring the fact that it doesn't actually make sense because a strikethrough line has a specific meaning,  it makes  scripts harder to read. Considering that there is already a squiggle going along the length of the substitution, I'm not sure what purpose the strikethrough serves.

**Comment by felipecrs** [comment]
Well, the strikethrough behavior is not caused by vscode-shellcheck. The extension only tells VS Code that it's deprecated, and VS Code renders it as it wants.

But I'll take a look if there is any option, and I'll let you know.

**Comment by sweetgiorni** [comment]
Ah okay, that makes more sense. I think the intended use case there is for deprecated functions, classes,  etc. where some reduced legibility may be intentional.

**Comment by felipecrs** [comment]
I think it's feasible to add an configuration to let users select which rules should be considered as deprecated or not.

**Comment by felipecrs** [comment]
Ok, there is a better alternative: disable this rule for the entire workspace. What do you think?

**Comment by sweetgiorni** [comment]
Haha, well... it's not that I don't want to know about the deprecation, I just want to it to be a squiggle like everything else. But I'm getting nit-picky now; how about I send a PR for what you described earlier, an option to stop reporting it to VS Code as deprecated?

**Comment by felipecrs** [comment]
Sure, I suggest it to be like:

```jsonc
{
  "shellcheck.deprecatedRules": [
    "SC2006",
    "SC2007",
    "SC2186",
    "SC2196",
    "SC2197"
  ] // default value but overridable
}
```

Or you can come up with a more complex object, such as:

Default object:
```jsonc
{
  "shellcheck.deprecatedRules": {
    "SC2006": true,
    "SC2007": true,
    "SC2186": true,
    "SC2196": true,
    "SC2197": true
  }
}
```

And then one could set as:
```jsonc
{
  "shellcheck.deprecatedRules": {
    "SC2006": false,
  }
}
```

And the strategy would be to merge the user set object with the default object.

**Comment by antcodd** [comment]
VS Code has a setting to disable this strikethrough of deprecated code: ``"editor.showDepercated": false``.
I personally have it disabled globally but you can probably set it per language as well in the normal way.

**Comment by felipecrs** [comment]
That's really nice. For completeness:

```jsonc
// .vscode/settings.json
{
  "[shellscript]" {
     "editor.showDeprecated": false
  }
}
```

**Comment by felipecrs** [comment]
So, I think this can be closed.
