### ISSUE TITLE
Publish platform specific extensions

### ISSUE THREAD

**Issue by GitMensch** [vscode-shellcheck/vscode-shellcheck#358]
ShellCheck is a relative "big" extension since 0.10.0 because of the bundled native binaries. It may be reasonable to switch to [platform specific publishing](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions), at least after the release bot (https://github.com/felipecrs/semantic-release-vsce/issues/189) and osvx (https://github.com/eclipse/openvsx/issues/336) handles those.

**Comment by felipecrs** [comment]
Thank you for reporting this. There are definitely plans to do that.

And as you correctly captured: after https://github.com/felipecrs/semantic-release-vsce/issues/189. I think we could keep publishing the big one as today to `ovsx`, if the support does not arrive in time.

**Comment by sryze** [comment]
+1, I too noticed that there are unnecessary binaries for other platforms that occupy hundreds of megabytes. It would be nice to not have them on disk if not needed, especially given that VS Code keeps old versions of extensions.

![shellcheck-redundant-os-arch-binaries](https://user-images.githubusercontent.com/4525736/194599493-5fe3cd15-30e6-43c5-b02e-d99bdcbef09d.png)

**Comment by felipecrs** [comment]
Wow. The macOS binaries are really big, I didn't know it.
