### ISSUE TITLE
declare multiple vars gives error

### ISSUE THREAD

**Issue by alanlivio** [vscode-shellcheck/vscode-shellcheck#464]
The following code, 
```
declare IS_{MAC,UBU,WIN,WIN_WSL,WIN_MSYS,WIN_GITBASH}=false
```

give this error

![image](https://user-images.githubusercontent.com/604808/151659685-5e620e06-50e4-452f-9894-b4e702d7f0e4.png)

**Comment by felipecrs** [comment]
I can't replicate:

![image](https://user-images.githubusercontent.com/29582865/151663169-27e6583c-25d9-4604-9d59-00ba207088ad.png)

But regardless, by looking at the problem message, I don't think this is thrown by ShellCheck. Check your other Shell Script extensions.

**Comment by alanlivio** [comment]
I also use [shell-format](https://github.com/foxundermoon/vs-shell-format.git).
I disable and enable both extensions then the errors disappear.
Thank you for you time @felipecrs
