### ISSUE TITLE
# shellcheck source=somefile support

### ISSUE THREAD

**Issue by dotnetCarpenter** [vscode-shellcheck/vscode-shellcheck#534]
When I source a bash script in my project, I always get the following warning:

>Not following: somefile was not specified as input (see shellcheck -x).shellcheck(SC1091)
>https://github.com/koalaman/shellcheck/wiki/SC1091

Adding the correct code as specified, does not change the problem being highlighted

```bash
# shellcheck source=osht.sh
source osht.sh
```

ShellCheck: v0.18.10
vscode: 1.65.2

**Comment by felipecrs** [comment]
This is from ShellCheck itself, not from the extension. To solve it, I recommend you create a file named  `.shellcheckrc` in the root of your project and put the following inside it:

```
external-sources=true
```

Or, you can configure the extension to run ShellCheck with `--external-sources`:

![image](https://user-images.githubusercontent.com/29582865/160497598-c8730ec8-b6a8-427b-a797-f2cff415f3a2.png)

**Comment by dotnetCarpenter** [comment]
Thank you @felipecrs, I didn't see there is a "Custom Args" section.
