### ISSUE TITLE
Not working together with the SSH FS extension

### ISSUE THREAD

**Issue by yooonie** [vscode-shellcheck/vscode-shellcheck#536]
hello,
i encounter an issue with Shellcheck :

It work like a charm on local folder, but when i use SSH FS extension to open a remote folder, i have an error who tell me shellcheck program was not found : 
![image](https://user-images.githubusercontent.com/45107861/160568627-70c4ebcb-eedf-4acd-9f8e-5e90a160051e.png)

This is my actual configuration : 

![image](https://user-images.githubusercontent.com/45107861/160570544-82feebe6-ec5d-4a40-85de-33c4fe34afa1.png)

I have tried to set the executable path pointing on the last version of shellcheck, but with no success :/

Thanks for help ^^

**Comment by felipecrs** [comment]
This one?

https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs

**Comment by felipecrs** [comment]
As mentioned in their docs:

> This works seamlessly with extensions using the vscode.workspace.fs API (added in VS Code 1.37.0), although not all extensions switched over, especially ones making use of binary files.

The ShellCheck is one of them. And I'm not sure if by simply switching to the vscode.workspace.fs would help.

**Comment by timonwong** [comment]
I'll take a look

**Comment by yooonie** [comment]
> This one?
> 
> https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs

Hello,
Yes, this one.

**Comment by timonwong** [comment]
@yooonie Can you have a try the PR build: https://github.com/vscode-shellcheck/vscode-shellcheck/suites/5859040701/artifacts/197409539?

If the link above does not work: visit https://github.com/vscode-shellcheck/vscode-shellcheck/actions/runs/2064108988:
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/1398228/160814279-1df572af-2c2d-45af-bf55-600a039a90a0.png">

**Comment by yooonie** [comment]
@timonwong tested today, it work fine ^^
big thanks
