### ISSUE TITLE
SC1091 highlighted for absolute paths

### ISSUE THREAD

**Issue by willmcenaney** [vscode-shellcheck/vscode-shellcheck#585]
`source /etc/config.config` gets highlighted incorrectly as breaking SC1091.

It also seems as though this will flag for other test cases and may not work with the `# shellcheck source=` directives?

**Comment by felipecrs** [comment]
Hey @willmcenaney, can you try with the shellcheck binary (without the extension) to see if the same behavior remains? Because if it does, you need to report it at: 

https://github.com/koalaman/shellcheck

**Comment by felipecrs** [comment]
Closing due to lack of response.
