### ISSUE TITLE
SC1091 - not honoring "source-path" from .shellcheckrc

### ISSUE THREAD

**Issue by jmccann** [vscode-shellcheck/vscode-shellcheck#607]
If you provide `source-path` in a `.shellcheckrc` file and run `shellcheck` from terminal it works fine.

But when using the extension it shows a warning when doing something like

```
. "${SCRIPTDIR}/../../shared/scripts/lib.sh"
```

You can reproduce with the following script:

```sh
#!/bin/sh

cat > .shellcheckrc <<EOF
enable=all
source-path=SCRIPTDIR/../../shared/scripts
EOF

mkdir -p tasks/shared/scripts tasks/test/scripts

cat > tasks/shared/scripts/lib.sh <<EOF
#!/bin/sh

echo "hello world"
EOF

cat > tasks/test/scripts/test.sh <<EOF
#!/bin/sh

SCRIPTDIR="\$( cd "\$( dirname "\$0" )" && pwd )"

. "\${SCRIPTDIR}/../../shared/scripts/lib.sh"
EOF

shellcheck -x tasks/test/scripts/test.sh
```

You will see the script run `shellcheck` w/o warnings.  But if you then browse to `tasks/test/scripts/test.sh` in vscode with this extension you will see a warning.

![Screen Shot 2022-06-02 at 2 47 39 PM](https://user-images.githubusercontent.com/1228349/171725956-af1eacb0-3d7d-484d-af07-e02a93bfa327.png)

I do have `Shellcheck: Use Workspace Root As Cwd` enabled.

**Comment by felipecrs** [comment]
> Shellcheck: Use Workspace Root As Cwd

What if you disable it?

**Comment by felipecrs** [comment]
As you used `shellcheck -x`, you should also instruct your VS Code to call shellcheck that way:

```json
{
    "shellcheck.customArgs": [
        "-x"
    ]
}
```

Alternatively, you can add: `external-sources=true` to your shellcheckrc.

**Comment by jmccann** [comment]
So thanks for the tips.  I removed `-x` and added `external-sources=true` to the config.

Running `shellcheck` from terminal shows no errors.

I had VSCode closed.  I opened it after the above changes.  I still see it prompting a warning in the file.  I made changes and saved and still shows the warning.  The warning does seem to have changed.  It's still SC1091 but now it says:

> Not following: ./../../shared/scripts/lib.sh: openBinaryFile: does not exist (No such file or directory)shellcheck(SC1091)

The file does exist

```
» tree
.
├── reproduce.sh
└── tasks
    ├── shared
    │   └── scripts
    │       └── lib.sh
    └── test
        └── scripts
            └── test.sh

```

Here's the slightly updated script

```sh
#!/bin/sh

cat > .shellcheckrc <<EOF
enable=all
external-sources=true
source-path=SCRIPTDIR/../../shared/scripts
EOF

mkdir -p tasks/shared/scripts tasks/test/scripts

cat > tasks/shared/scripts/lib.sh <<EOF
#!/bin/sh

echo "hello world"
EOF

cat > tasks/test/scripts/test.sh <<EOF
#!/bin/sh

SCRIPTDIR="\$( cd "\$( dirname "\$0" )" && pwd )"

. "\${SCRIPTDIR}/../../shared/scripts/lib.sh"
EOF

shellcheck tasks/test/scripts/test.sh
```

**Comment by jmccann** [comment]
>> I do have `Shellcheck: Use Workspace Root As Cwd` enabled.

> PS: I recommend you disable it, unless you need it.

So, unticking this option plus your fixes solved this issue for me!  Your comment seemed more a suggestion but it seems have had `Shellcheck: Use Workspace Root As Cwd` enabled was also part of the problem.  Thanks!! 👏
