### ISSUE TITLE
Sponsor link

### ISSUE THREAD

**Issue by isidorn** [vscode-shellcheck/vscode-shellcheck#623]
VS Code PM here :wave:

Consider using this for a sponsor link https://github.com/sponsors/felipecrs
Currently the sponsor link points to the Github repo, which requires one more click

**Comment by felipecrs** [comment]
Hi there @isidorn 👋

In fact, I considered this earlier, but I'm not the only maintainer of the extension. There is also @timonwong (the author), and he may want to create a sponsor profile (in GitHub or in another platform in the future), so I decided not to directly put my link there.

The best would be to have a sponsor's page in GitHub for the project itself, like https://github.com/vscode-shellcheck/vscode-shellcheck/sponsor, that would list everyone's profile.

As there isn't such a thing yet, I decided to put the GitHub homepage of the project.

Thanks for the tip, but I hope that's okay for now.

Another option would be for the VS Code to accept multiple links, like:

```json
{
  "sponsor": [
    {
      "url": "https://github.com/sponsors/felipecrs",
    }, 
    {
      "url": "@timonwong's url"
    }
  ]
}
```

Although I still feel that the first option (a sponsor's page per project) would be simpler.

**Comment by isidorn** [comment]
@felipecrs yup that's okay of course. Yeah a sponsor page would be best :)

We considered supporting multiple urls, but the UI then gets tricky. So we decided to not have it for now.

**Comment by felipecrs** [comment]
@isidorn I just created a feature suggestion for GitHub on this: https://github.com/orgs/github-community/discussions/18281.

I will close this issue for now, and if it gets implemented, we will be the firsts to change. Thank you!

**Comment by felipecrs** [comment]
I looked at that too (https://github.com/sponsors/vscode-shellcheck), but it's a different purpose. It's a company sponsor profile: i.e. the money would be sent to the company, not to particular users.
