### ISSUE TITLE
Consider becoming a verified publisher

### ISSUE THREAD

**Issue by isidorn** [vscode-shellcheck/vscode-shellcheck#624]
VS Code PM here 👋 

Consider becoming a verified publisher. More details here
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher

Thanks

**Comment by felipecrs** [comment]
We don't have a domain, unfortunately. And I believe it would be too much to buy a domain just for this VS Code extension.

The closest thing, if not that, would be @koalaman's shellcheck.net, but this project isn't maintained by him, and I believe it would be mistaken to display something like _Timon Wong has verified ownership of shellcheck.net_.

**Comment by isidorn** [comment]
Makes sense, thanks for letting us know.

**Comment by felipecrs** [comment]
Thank you for the suggestion though, have a great day!
