### ISSUE TITLE
Feature request: new setting: `useClosestShellcheckrcAsCwd`

### ISSUE THREAD

**Issue by papb** [vscode-shellcheck/vscode-shellcheck#641]
The `shellcheck.useWorkspaceRootAsCwd` is great but still I'd like something better. I want to have a way to tell VSCode to use as cwd the closest ancestor folder that contains a file named `.shellcheckrc` (and use it as options, of course).

This way I can work on both repos `foo` and `bar` by opening just one VSCode window at `repos`, instead of being forced to open two windows:

```
/home/papb/
      └── repos/
          ├── foo/
          │   ├── .git
          │   ├── .shellcheckrc
          │   └── lib/
          │       ├── something.sh
          │       └── something-else.sh
          └── bar/
              ├── .git
              ├── .shellcheckrc
              └── lib/
                  ├── something.sh
                  └── something-else.sh
```

**Comment by felipecrs** [comment]
For me it already works just fine with the default configuration (i.e. `useWorkspaceRootAsCwd: false`):


https://user-images.githubusercontent.com/29582865/187497224-59cf8773-fb4a-4ad6-a816-c740b510750c.mp4

Can you please let me know if this is still needed?

**Comment by felipecrs** [comment]
Closing due to lack of response.
