### ISSUE TITLE
"The shellcheck program was not found" on macOS

### ISSUE THREAD

**Issue by slhck** [vscode-shellcheck/vscode-shellcheck#651]
I have been using this extension for a while now, successfully, but now the error appears:

> The shellcheck program was not found (not installed?). Use the 'shellcheck.executablePath' setting to configure the location of 'shellcheck'

I have not configured the `executablePath`, as I have never needed to do this before.

The vscode-shellcheck extension settings are not changed from the defaults (there is nothing in `settings.json` related to shellcheck).

Shellcheck is installed at `/opt/homebrew/bin/shellcheck`, and this is also part of my `$PATH`. But I would assume it will pick a bundled executable if that path is not specified.

I am using macOS 12.4 with VS Code 1.68.1 and vscode-shellcheck v0.19.5.

**Comment by slhck** [comment]
Restarting VS Code seems to have fixed the problem …

**Comment by felipecrs** [comment]
Hm... weird. But if we can't reproduce the issue, there is not much we can do. =/

**Comment by slhck** [comment]
No worries. Like I said, a restart solved it!
