### ISSUE TITLE
Hover  over shell commands manpage not appearing - Fedora 36

### ISSUE THREAD

**Issue by s-fairchild** [vscode-shellcheck/vscode-shellcheck#704]
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:25.715Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.18.17-200.fc36.x86_64

The shell check linting is working
![Screenshot from 2022-08-23 10-47-47](https://user-images.githubusercontent.com/67697325/186190232-ca16dbe7-850b-442c-a53d-9f6abd34ff52.png)

But the hover over man/help pages aren't appearing for commands
![Screenshot from 2022-08-23 10-53-11](https://user-images.githubusercontent.com/67697325/186190609-0400ef62-28de-4c61-b4f6-21bb7a4ebc60.png)
<br>
```bash
[root@host ~]# rpm -q ShellCheck
ShellCheck-0.7.2-5.fc36.x86_64
[root@host ~]# rpm -q ShellCheck 
ShellCheck-0.7.2-5.fc36.x86_64
[root@host ~]# rpm -ql ShellCheck 
/usr/bin/shellcheck
/usr/lib/.build-id
/usr/lib/.build-id/52
/usr/lib/.build-id/52/0642150b22d1c4596f47a2a565a996b8de156e
/usr/share/doc/ShellCheck
/usr/share/doc/ShellCheck/README.md
/usr/share/licenses/ShellCheck
/usr/share/licenses/ShellCheck/LICENSE
/usr/share/man/man1/shellcheck.1.gz
```

**Comment by felipecrs** [comment]
This was never a feature of this extension, it should come from some other one.

**Comment by s-fairchild** [comment]
@felipecrs I apologize, I didn't realize ShellCheck wasn't providing this feature for me on my other machines.

This project and vscode extension provides the feature.
https://github.com/bash-lsp/bash-language-server

Sorry for any inconvenience, and I appreciate your fast response that helped me realize this.

**Comment by felipecrs** [comment]
It's alright, thanks for letting us know which was the other extension. Have a good day!
