### ISSUE TITLE
Bundle darwin arm64 (Apple Silicon) binary for shellcheck

### ISSUE THREAD

**Issue by timonwong** [vscode-shellcheck/vscode-shellcheck#720]
Steps:
- [x] Create a repo to build/download shellcheck
- [x] <del>Add a self-hosted github runner for build M1 binaries</del>
- [x] Modify bindl.config.js to use our bundled shellcheck binaries (instead of the original one) #725

**Comment by timonwong** [comment]
I'll do that when my hands free

**Comment by felipecrs** [comment]
Shouldn't we push a PR to ShellCheck instead?

**Comment by timonwong** [comment]
@felipecrs There is no Apple Silicon hardware yet, and GHC has problems cross-compiling. So the only way is a real Apple Silicon github actions runner.
