### ISSUE TITLE
Malformed `shellcheck.exclude` arrays can cause all checks to be ignored

### ISSUE THREAD

**Issue by LeuschkeTressa** [vscode-shellcheck/vscode-shellcheck#739]
# In short

Having at least one malformed entry in the `shellcheck.exclude` array in `settings.json` can cause ShellCheck to ignore all checks. This will happen silently, without any error message or hint to the user.

# Details

`settings.json`: examples of _correct_ `shellcheck.exclude` arrays: ShellCheck will work as expected.
```json
"shellcheck.exclude": [ "1113" ], 
"shellcheck.exclude": [ "1113", "1114" ], 
```

`settings.json`: examples of _malformed_ `shellcheck.exclude` arrays: ShellCheck will silently ignore all checks.
```json
"shellcheck.exclude": [ "1113X" ], 
"shellcheck.exclude": [ "someString" ],
"shellcheck.exclude": [ "someString", "1113" ],
"shellcheck.exclude": [ "1113", "someString"],
```

This problem is particularly hard for the user to trouble-shoot:
* the user experience will be that ShellCheck seems to be de-activated; the user simply sees no trace of ShellCheck
* there will be no error message pop-up, and no error message or hint in the logs (`Code/logs/`) or the VS Code _Problems_ or _Output_ panes
* a plugin re-install won't help since that won't remove/reset `shellcheck.*` settings in `settings.json`

Related: https://github.com/vscode-shellcheck/vscode-shellcheck/issues/740 (the plugin settings UI doesn't validate the user input, possibly leading to malformed `shellcheck.exclude` settings being written to `settings.json`)

# Steps to reproduce

* enter any of the malformed `shellcheck.exclude` examples above into `settings.json` and save the file
* open a shell script file

# Expected behaviour

* in the opened shell script file, ShellCheck shows any errors (with no checks ignored)
* an error message is presented to the user, informing that `shellcheck.exclude` in `settings.json` has errors

# Actual behaviour

* ShellCheck will ignore all checks, leaving the user with no sign of ShellCheck
* no error message or hint in the logs is produced

# Versions

**vscode-shellcheck**: v0.22.0
**shellcheck executable[1]:** 0.8.0
**VS Code:** 1.71.2, arm64

[1]: using an external executable and the bundled binaries have the same effect

**Comment by felipecrs** [comment]
Unfortunately, [validation based on regular expressions](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration:~:text=pattern%20for%20restricting%20strings%20to%20a%20given%20regular%20expression) does not seem to work at all.
