### ISSUE TITLE
Entering a new item in Ignore Patterns via the Settings UI is not ignored

### ISSUE THREAD

**Issue by chrisr87** [vscode-shellcheck/vscode-shellcheck#790]
In the "Ignore Patterns" section of the Settings UI, if I add a new item and set it to `true`, it saves that value as a string:
```
    "shellcheck.ignorePatterns": {
        "**/*.bashrc": "true",
    }
```
and as a result, shellcheck will not ignore the item like you expect it to.

Not sure if this is an issue with shellcheck or how vscode parses the items set in the Settings UI. But you can manually edit the settings.json and replace `"true"` with `true` and it does work.

**Comment by felipecrs** [comment]
Thanks for reporting!
