### ISSUE TITLE
Stop downloading binaries for every single architecture in all hosts

### ISSUE THREAD

**Issue by babaric-dev** [vscode-shellcheck/vscode-shellcheck#796]
Here is what is in shellcheck's extension now:
```
binaries/
    darwin/
        arm64/
            shellcheck
        x64/
            shellcheck
    linux/
        arm/
            shellcheck
        arm64/
            shellcheck
        x64/
            shellcheck
    win32/
        x32/
            shellcheck.exe
```

Suppose I have an x64 Linux machine, the extension should only download `binaries/linux/x64/shellcheck`, saving 120MB (~85%) disk space.

Similarly, if the host is Windows, only `binaries/win32/x32/shellcheck.exe` should be downloaded.

4 solutions to this:
1. Download only that 1 binary package in the `.vsix` (saves bandwidth too but not feasible(?))
2. Download all binaries and remove irrelevant binaries (works but wastes bandwidth)
3. Setting to point shellcheck to use an external binary installed in the system (requires extra setup but can save disk space further by using system binaries)
4. Download binary seperately (check does binary exist everytime, if not, download the suitable binary)

I think solutions 3 and 4 are best. Or maybe we can have solution 5 by combining solution 3 and 4 (best of the best!).

Temporary solution:
User removes the unused binary him/herself (works, but need to do so every update)

Hope that this will get implemented soon.

**Comment by felipecrs** [comment]
Although the ultimate fix is https://github.com/vscode-shellcheck/vscode-shellcheck/issues/358, your suggestion can be implemented before it. PRs are accepted.

**Comment by babaric-dev** [comment]
So, to use the platform-specific extension API, we must avoid binaries?

**Comment by felipecrs** [comment]
No, but with the platform-specific API we can distribute one vsix for each platform, so that you will download only the vsix which contains the binary for this platform.

Just to mention, this extension does not download the binaries for you, its package already comes with all the binaries inside it.

But as you mention, we can inject some code in the startup of the extension so that everytime it starts it also tries to remove the binaries for other platforms, which at least helps to save disk space.

**Comment by babaric-dev** [comment]
I see. But what is stopping us from doing so (implementing platform-specific API)? I can't spot problems/limitations in #358.

**Comment by felipecrs** [comment]
Missing:

- https://github.com/felipecrs/semantic-release-vsce/issues/189
- https://github.com/felipecrs/bindl/issues/189

**Comment by babaric-dev** [comment]
So we have nothing missing. It is just the related projects have missing features. Am I right?

**Comment by felipecrs** [comment]
Well, kinda. Once these projects close these two issues we will have to implement their new features here too.

**Comment by babaric-dev** [comment]
So we'll just have to wait.

**Comment by babaric-dev** [comment]
So, should we discuss solution 3 + 4 (a.k.a. solution 5) instead of something impossible to do now?

**Comment by felipecrs** [comment]
I'll close this in favor of #358 for now. PRs are still accepted for implementing the following until #358 is not fixed:

- Delete unused binaries at extension initialization in order to save disk space

**Comment by felipecrs** [comment]
> Anyway, hope my suggestion helps!

We have no plans to reimplement all this logic. It's probably more difficult to do it than doing the proper way (#358).

**Comment by babaric-dev** [comment]
How about the feature of not downloading any binaries when `shellcheck.executablePath` is set? It seems that having any extra executable is quite pointless.

**Comment by GitMensch** [comment]
As noted:
* there is no binary downloaded by the extension
* all binaries are included as part of the build process into the .vsix which is distributed (quite big, so for now only install/update when on an unrestricted network)
* a platform specific vsix means there are _multiple_ vix build and distributed (you only download the one needed, nice side effect: there can be an "all OS ones" - which does not ship the binary but instead needs `shellcheck.executablePath` to be set)
* until the "blockers" are solved a PR is accepted that checks on activation of the extension (= after download) if there are unused binaries in the extension directory and deletes them

**Comment by felipecrs** [comment]
Thanks @GitMensch, that's right.

**Comment by felipecrs** [comment]
> a platform specific vsix means there are multiple vix build and distributed (you only download the one needed, nice side effect: there can be an "all OS ones" - which does not ship the binary but instead needs shellcheck.executablePath to be set)

BTW, I'm reading the documentation at https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions at I don't think it's possible to have a "all OS ones" variant. But, for all the platforms that we don't have a binary for, the vsix will contain no binaries.
