### ISSUE TITLE
Failed to run shellcheck: [undefined] Unexpected response from ShellCheck

### ISSUE THREAD

**Issue by rabin-io** [vscode-shellcheck/vscode-shellcheck#804]
I tried to run this in VSCODE and shellcheck via podman and got this error,

```
Failed to run shellcheck: [undefined] Unexpected response from ShellCheck: ShellCheck - shell script analysis tool version: v
```

When I debugged this, I found out the regex for catching the version didn't match 

```
# shellcheck -V
ShellCheck - shell script analysis tool
version: v0.8.0-72-gd71d6ff
license: GNU General Public License, version 3
website: https://www.shellcheck.net
```

and the regex don't have the `v` in it, 

```
version: ((?:\d+)\.(?:\d+)(?:\.\d+)*)
```

So for now I'm caching the `-V` parameter and returning a fix value, to allow the extension to work.

```sh
#!/bin/bash

if [[ $1 == '-V'  ]]; then
    echo version: 0.8.0
    exit
fi

exec podman run -i --rm -v "${PWD}:/mnt:ro" koalaman/shellcheck:latest "$@"
```

**Comment by felipecrs** [comment]
Also consider enabling this option:

![image](https://user-images.githubusercontent.com/29582865/199774938-bca33963-662d-4b71-bda6-7e0a04966758.png)
