### ISSUE TITLE
Don't download any shellcheck binaries if shellcheck present in PATH or "shellcheck.executablePath" has been set

### ISSUE THREAD

**Issue by J-Lakeman** [vscode-shellcheck/vscode-shellcheck#845]
I appreciate this extension a lot, but it doesn't make much sense if every extension update redownloads the binary, IMHO. Especially if either `shellcheck` is present in `PATH` or `shellcheck.executablePath` has been set.
Alternatively / Additionally, the extension should prompt whether to download the binary in general.

The suggested changes could save a lot of bandwidth and disk storage. Packaged Linux or macOS binaries of `shellcheck` take up way less disk space than the downloaded ones. Maybe the packaged ones should be preferred.

**Comment by felipecrs** [comment]
Is this a problem even after https://github.com/vscode-shellcheck/vscode-shellcheck/pull/805? The extension packages are quite small:

![image](https://user-images.githubusercontent.com/29582865/205459455-b0e363ca-e319-469f-8468-f4cb5bade62c.png)

**Comment by felipecrs** [comment]
> Alternatively / Additionally, the extension should prompt whether to download the binary in general.

If you mean to remove the binary from the extension package and make a logic to perform what you refer to, like downloading the binary, that's not something I'm keen to do.

The current manner is recommended by Microsoft. It works with less user interaction or even tinkering.

**Comment by felipecrs** [comment]
Therefore I'm closing this issue. But I'm happy to continue the discussion if you want to argue.

**Comment by felipecrs** [comment]
Since v0.29.0 we now publish a vsix without any binaries. You can download it from GitHub Releases and then install in your VS Code in case you prefer using it. Example:

https://github.com/vscode-shellcheck/vscode-shellcheck/releases/download/v0.29.0/shellcheck-0.29.0.vsix

https://user-images.githubusercontent.com/29582865/205779876-083aa570-44ce-4a5d-81fd-52f2fd57fbfc.mp4

**Comment by j-lakeman** [comment]
Sorry for not replying.
Appreciate your work, the binary is tiny now and only the specific one is downloaded. Totally happy with that!
