### ISSUE TITLE
Include some sort of output in the VScode 'Output' pane after running `shellcheck`

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [vscode-shellcheck/vscode-shellcheck#908]
I'm currently having an issue where I can't figure out why Shellcheck isn't running (https://github.com/vscode-shellcheck/vscode-shellcheck/discussions/907). One thing contributing to my confusion there is that explicitly invoking the `shellcheck.runLint` command has ... no observable effect, whatsoever. I can't tell if `shellcheck` isn't being found, is crashing, or isn't ever being invoked in the first place.

More debugging output would be nice — i.e. something like

```
[2023-01-30T19:11:09.888Z] [INFO] shellcheck (bundled) version: 0.9.0
[2023-01-30T19:11:09.888Z] [INFO] explicit shellcheck.runLint invoked by user
[2023-01-30T19:11:09.888Z] [INFO] using bundled shellcheck
[2023-01-30T19:11:09.888Z] [INFO] shellcheck response:

In ./api_annotate_dead_code.zsh line 10:
if [[ -f reanalyze.log ]]; then
   ^--------------------^ SC2169: In dash, [[ ]] is not supported.


In ./api_annotate_dead_code.zsh line 11:
...

[2023-01-30T19:11:09.888Z] [INFO] shellcheck binary exited with exit-code 1
```

... so on and so forth.

**Comment by timonwong** [comment]
@ELLIOTTCABLE In #1035 a diagnostic command is provided, besides, when the logging level of shellcheck is "trace", it can show the response from shellcheck binary (though in JSON)
