### ISSUE TITLE
Shellcheck is replacing code with nonsense snippet template

### ISSUE THREAD

**Issue by phoenixeliot** [vscode-shellcheck/vscode-shellcheck#914]
Type: <b>Bug</b>

Shellcheck is replacing this code:
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
```

With this:
```
#!/bin/sh
. <>
	${TM_SELECTED_TEXT}
</>
```

on save, automatically. This is occurring when using this nextjs template: https://github.com/theodorusclarence/ts-nextjs-tailwind-starter when editing the `.husky/commit-msg` file.

I identified this as being a Shellcheck problem using Extension Bisect.

Extension version: 0.29.3
VS Code version: Code 1.74.3 (Universal) (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 12, 17|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by felipecrs** [comment]
Does it happen when running shellcheck via CLI?

**Comment by felipecrs** [comment]
Ok, I just confirmed this bug.

**Comment by felipecrs** [comment]
Thanks for reporting the issue, @phoenixeliot. :)
