### ISSUE TITLE
shellcheck runs on type even if it should run on save

### ISSUE THREAD

**Issue by misaki-web** [vscode-shellcheck/vscode-shellcheck#916]
Using vscode 1.74.3 with vscode-shellcheck 0.29.3, I set shellcheck to run on save:

![vscode-shellcheck "run on save" setting](https://user-images.githubusercontent.com/64830812/216659416-26a35ddf-1de2-4bbc-85fa-1fbb91b37a52.png)

However, it keeps running on type. For example, right after typing "if", it complains of errors, but the file was not saved:

![vscode-shellcheck running on save](https://user-images.githubusercontent.com/64830812/216662930-e223c5b8-1993-4101-b2a2-dd2233746862.png)

**Comment by felipecrs** [comment]
Are you sure this setting isn't being overwritten by machine/language/workspace settings?

**Comment by misaki-web** [comment]
In my user settings (`/home/user/.config/Code/User/settings.json`), I have:

```json
"shellcheck.run": "onSave",
```

My workspace settings (opened with `workbench.action.openWorkspaceSettingsFile`) are empty:

```json
{
    "folders": [
        {
            "path": "/path/to/workspace"
        }
    ],
    "settings": {}
}
```

About language settings (opened with `workbench.action.configureLanguageBasedSettings`), there are no settings about shellcheck (the search `@lang:shellscript shellcheck` returns no results).

Are there other settings to check?

**Comment by felipecrs** [comment]
Awesome. I'll close this issue then.

**Comment by skovhus** [comment]
bash-language-server / Bash IDE maintainer chipping in: setting `bashIde.shellcheckPath` to an empty string disables the ShellCheck linting. 

But I would love our two projects to join forces that all editors (Atom, Eclipse, Emacs, Helix, JupyterLab, Neovim, Sublime Text, Vim, Visual Studio Code, Oni, and editors that I forgot) can get the same great shellcheck linting experience as provided by `vscode-shellcheck`. ;)
