### ISSUE TITLE
shellcheck still active after switching language mode

### ISSUE THREAD

**Issue by NorthboundTrain** [vscode-shellcheck/vscode-shellcheck#966]
VS-Code: 1.75.1
vscode-shellcheck: v0.29.4
shellcheck: 0.9.0
MacOS: 12.5

I have a perl script file with no extension that VS Code is mistakenly identifying as a shell script (which is a separate problem). Because of this, shellcheck is run when the file is opened, as expected, and errors are reported, also as expected (since it's perl and not shell). When I manually change the language mode to 'Perl (perl)', though, the shellcheck errors remain. If I reload the window via "Developer: Reload Window" then they go away.

**Comment by felipecrs** [comment]
For me it's working fine:

https://user-images.githubusercontent.com/29582865/222785184-693f3ab0-b1da-41ec-aafc-c9a0bba00e20.mp4

Can you check if you are not being affected by https://github.com/bash-lsp/bash-language-server/issues/711?

**Comment by NorthboundTrain** [comment]
That was the issue -- thank you!
