### ISSUE TITLE
Cant figure out how to configure this extension to find/lint *.bats files

### ISSUE THREAD

**Issue by freol35241** [vscode-shellcheck/vscode-shellcheck#983]
Hi, thanks for this extension!

I am trying to figure out how to use this for linting *.bats-files. (https://github.com/bats-core/bats-core)

Support in shellcheck was added here: https://github.com/koalaman/shellcheck/pull/1469

Any help would be appreciated!

**Comment by felipecrs** [comment]
Simply mark the files as Shell Script files, did you try that?

**Comment by freol35241** [comment]
Ahh! That works a charm! Thanks for the prompt reply and keep up the good work 🍾

**Comment by freol35241** [comment]
And for anyone else getting lost on this:

Adding something like this to `.vscode/settings.json` will make the "marking" permanent
```json
{
    "files.associations": {
        "*.bats": "shellscript"
    }
}
```
